user:
  kafka:
    server: localhost:9092
    topic: user
    partition: 3
    replicas: 3
    store: user-state-store
    retention: -1
    acks: all
    retries: 10
    requestimeout: 5000
    batch: 163850
    linger: 100
    max-in-flight: 1
    client-id: apollo-user
    group-id: apollo-user-group
    offset: latest

spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: apollo-user
      function:
        definition: userProcessor;
        bindings:
          userProcessor-in-0.destination: user
          userProcessor-out-0.destination: user-states
