user:
  kafka:
    server: localhost:9092
    topic: user
    partition: 1
    replicas: 1
    store: user-state-store
    retention: -1
    acks: all
    retries: 10
    requestimeout: 5000
    batch: 163850
    linger: 100
    max-in-flight: 1
    client-id: apollo-user
    group-id: apollo-user-group
    offset: earliest

spring:
  cloud:
    function:
      definition: userStateProcessor;
    stream:
      kafka:
        streams:
          binder:
            functions:
              userStateProcessor:
                application-id: apollo-user
      bindings:
        userStateProcessor-in-0.destination: ${user.kafka.topic}
        userStateProcessor-out-0.destination: ${user.kafka.store}
server:
  port: 8088
