user:
  kafka:
    server: localhost:9092
    topic: user
    partition: 1
    replicas: 1
    store: user-state-store
    retention: -1
    acks: all
    retries: 10
    requestimeout: 5000
    batch: 163850
    linger: 100
    max-in-flight: 1
    client-id: apollo-user
    group-id: apollo-user-group
    offset: latest

spring:
  cloud:
    function:
      definition: userProcessor;
    stream:
      kafka:
        streams:
          binder:
            application-id: apollo-user
      bindings:
        userProcessor-in-0.destination: user
        userProcessor-out-0.destination: user-states
server:
  port: 8080
